# Generated by Django 4.2.16 on 2024-11-23 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comapp', '0002_alter_device_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='inactive', max_length=50),
        ),
    ]
